# NumPy

In [ ]:
import numpy as np

## Create an Array
Write a Python program that creates an integer array with 4 elements of type unsigned int16 and prints the shape, the number of dimensions, and the length of each element in bytes.

In [1]:
import numpy as np

dArr=np.array([[5,7,9,23],[3,5,9,0]],dtype=np.uint16)
dArr.shape

print("Number of shape - dimensions:",dArr.shape, dArr.ndim)


print("Length of each element in bytes:", dArr.itemsize)

Number of shape - dimensions: (2, 4) 2
Length of each element in bytes: 2


## Create a 2D Array
Write a Python program that creates a $ 5 \times 2 $ integer array from a range between 100 to 200 such that the difference between each element is 10.

In [2]:
arr=[]
arrSub=[]
for i in range(100,200,10):
  arrSub.append(i)
  print(len(arrSub))
  if len(arrSub)==2:
    print(arrSub)
    arr.append(arrSub)
    arrSub=[]

print(arr)


1
2
[100, 110]
1
2
[120, 130]
1
2
[140, 150]
1
2
[160, 170]
1
2
[180, 190]
[[100, 110], [120, 130], [140, 150], [160, 170], [180, 190]]


In [3]:
# second way
arrx = np.arange(100, 200, 5)

# Reshape the array into a 5x2 array
reshaped_arr = arrx.reshape(4, 5)

# Print the reshaped array
print("5x2 Array:")
print(reshaped_arr)

5x2 Array:
[[100 105 110 115 120]
 [125 130 135 140 145]
 [150 155 160 165 170]
 [175 180 185 190 195]]


## Select Rows and Columns
Write a Python program to return the 2D array of odd rows and even columns from the given numpy array.

In [ ]:
a = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
a

In [4]:
a = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

# Split the array into 10 chunks
chunks = np.array_split(a, 10)

# Process each chunk
even_numbers = []
odd_numbers = []

for chunk in chunks:
    even_numbers.extend(chunk[chunk % 2 == 0])  # Append even numbers
    odd_numbers.extend(chunk[chunk % 2 != 0])

print(even_numbers)
print(odd_numbers)
arr
merge=np.array([even_numbers,odd_numbers])
print(merge)

print(np.array2string(merge, separator=','))

[6, 12, 18, 24, 30, 36, 42, 48, 54, 60]
[3, 9, 15, 21, 27, 33, 39, 45, 51, 57]
[[ 6 12 18 24 30 36 42 48 54 60]
 [ 3  9 15 21 27 33 39 45 51 57]]
[[ 6,12,18,24,30,36,42,48,54,60],
 [ 3, 9,15,21,27,33,39,45,51,57]]


## Compute Numerical Operations
Write a Python program that computes the sum, the element-wise multiplication, and the matrix multiplication of the given numpy arrays.

In [ ]:
a = np.array([[5, 6], [21, 18]])
b = np.array([[15, 33], [4, 7]])
a, b

## Split and Concatenate an Array
Write a Python program to split the given $ 8 \times 3 $ array into 4 equal-sized $ 2 \times 3 $ sub-arrays. Then, concatenate the splitted arrays vertically to rebuilt the original array.

In [52]:
a = np.arange(10, 34, 1).reshape(8, 3)
arrx=[]
rows = len(a)
columns = len(a[0])

arr_splited=np.split(a,4)

#all items
size = a.size

rows = len(a)
colums=len(a[0])
print(f"Total size: {size}--.{colums}--. {rows}   arr--: {arr_splited} ")

for sub_arr in arr_splited:
    print(sub_arr)

np.concatenate(arr_splited, axis=0)

Total size: 24--.3--. 8   arr--: [array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])] 
[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]
[[22 23 24]
 [25 26 27]]
[[28 29 30]
 [31 32 33]]


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

## Replace a Column
Write a Python program that replaces the second column from the given array with the new given column.

In [48]:
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
new_column = np.array([[10, 10, 10]])
a, new_column
a[1]=new_column
a


array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

Replace all occurrences > 6 with 99

In [55]:
for i in range(len(a)):          # Loop through rows
    for j in range(len(a[i])):   # Loop through columns
        if a[i][j] >10:         # Check if the value is 6
            a[i][j] = 99
a

array([[10, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

## Sort Rows and Columns
Write a Python program to sort the given 2D array in 2 scenarios: (1) Sort the rows; (2) Sort the columns.  

In [67]:
b = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
b

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [64]:
c=b
# sort independently. ,column.    12, 66,73
np.sort(c, axis = 0)

array([[34, 22, 12],
       [53, 43, 66],
       [82, 94, 73]])

In [69]:
# sort independently. ,rows.   , every items in every rows sorts
np.sort(b, axis =1
        )

array([[34, 43, 73],
       [12, 22, 82],
       [53, 66, 94]])